import Head from "next/head";
import Image from 'next/image'
import profilePic from '../public/me.png'
import profilePic1 from '../public/download.jpg'

import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>modifica 9/2/2022</h1>

        <h1>My photos component Image</h1>
        <Image
          src={profilePic}
          alt="My picture"
        // width={500} automatically provided
        // height={500} automatically provided
        // blurDataURL="data:..." automatically provided
        // placeholder="blur" // Optional blur-up while loading
        />
        <h1>Foto component Image da  dir locale publc</h1>
        <Image
          src={profilePic1}
          alt="foto da locale dir public"
        // width={500} automatically provided
        // height={500} automatically provided
        // blurDataURL="data:..." automatically provided
        // placeholder="blur" // Optional blur-up while loading
        />


        <h1>Foto component Image da  remoto layout intrinsic/img</h1>
        <Image
          src="https://pepenet.info/img/foto01.jpg"
          alt="altra foto"
          width={700}
          height={900}
          layout='intrinsic'
        />
        <h1>Foto component Image da  remoto layout fixed</h1>
        <Image
          src="https://pepenet.info/img/foto02.jpg"
          alt="altra foto"
          width={800}
          height={533}
          layout='intrinsic'
        />
        <h1>Foto component Image da  remoto layout responsive</h1>
        <Image
          src="https://pepenet.info/img/foto03.jpg"
          alt="altra foto"
          width={800}
          height={533}
          layout='intrinsic'
        />
        <h1>Foto component Image da  remoto layout responsive</h1>
        <Image
          src="https://pepenet.info/img/foto04.jpg"
          alt="altra foto"
          width={500}
          height={322}
          layout='intrinsic'
        />

        <h1>Foto component Image da  remoto layout intrinsic</h1>
        <Image
          src="https://pepenet.info/img/foto05.jpg"
          alt="altra foto"
          width={500}
          height={365}
          layout='intrinsic'
        />



        {posts.map((post) => {
          return (
            <div className={styles.card} key={post.id}>
              <h2>{post.title.rendered}</h2>
            </div>
          );
        })}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch("https://adminwp.pepenet.info/wp-json/wp/v2/posts");
  //const response = await fetch('https://jsonplaceholder.typicode.com/users')
  const data = await response.json();

  return {
    props: {
      posts: data,
    },
  };
}
